### ISSUE TITLE
[feature] Export to Discord Message (Clipboard), and others

### ISSUE THREAD

**Issue by elkolorado** [s2ward/talesoftibia.com#34]
# Description

Currently, users lack the ability to export chosen transcripts or books directly into Discord message with proper formatting. This feature request aims to streamline the process by providing users with the option to export their selected transcript or book to Discord, enhancing convenience and facilitating seamless sharing within Discord communities.

# Current state
Currently, sharing the chosen transcript or book, often comes with either crafted link, but more often it is screenshot from the tool itself.
![image](https://github.com/s2ward/talesoftibia.com/assets/25396329/a69d41a9-89de-4c0d-89a2-53cb66793d90)

# Proposed solution

User can export the transcript, selection of it, whole book, or selection of it using export option which will craft and copy message for discord purposes. 

### Abstract

```mermaid
sequenceDiagram
    participant User
    participant Application
    participant Clipboard
    participant Discord

    User->>Application: Selects transcript/book to export
    Application->>User: Presents export options
    User->>Application: Chooses "Discord Clipboard"
    Application->>Clipboard: Copies exported content
    Clipboard-->>User: Saves clipboard to user 
    User->>Discord: Opens Discord application
    Clipboard->>Discord: Pastes content into message
```
### Discord Output

![image](https://github.com/s2ward/talesoftibia.com/assets/25396329/c59b8794-2084-415b-9987-c66b951088d8)

### Reference for coloring using discord ticks

https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline
https://rebane2001.com/discord-colored-text-generator/

### Figuring out embedding image for npc/book into message

Currently, we would be able to achieve above with clipboard only, however embeding message from user is not allowed on discord. Bots can do that, so one could think of scenario, where instead of doing it on frontend side by user, user could first craft an embedded link that he would then pass to discord bot with a commend !transcript <link> and then bot would embed the selected transcript/selection of it into discord, eventually deleting the command comment to not pollute discord.

(ex. showing bot enchanced markdown with image)
![image](https://github.com/s2ward/talesoftibia.com/assets/25396329/7eb73f0a-655e-4764-8810-2d9ab5f099c9)

## Benefits

Not polluting discord with images, using discord to style it nicely, eventually leading to better search on discord - as embedded messages can now be searched

![image](https://github.com/s2ward/talesoftibia.com/assets/25396329/113aae02-3ebd-43c8-b2d7-e92000611813)

## Future

- discord embedding as above
- embedding in sites like so 
![image](https://github.com/s2ward/talesoftibia.com/assets/25396329/16c287f8-3344-4661-8c6c-89f08917917f)
- other suitable export options such as .csv, .json, etc.

# Tasks

- [ ] **Implement Export Option in Application:**
- [ ] **Design Export Options Menu:**
- [ ] **Integrate Clipboard Functionality:**
- [ ] **Craft Discord Message:**
- [ ] **Testing and Validation:**
- [ ] **Documentation and User Guidance:**
- [ ] **Discord Bot Integration (Optional Future Task):**
- [ ] **Embedding in Sites (Optional Future Task):**

**Comment by elkolorado** [comment]
PoC, below code for selecting text on the page, and getting helper tooltip for copying into discord
![chrome_bIurlISuxy](https://github.com/s2ward/talesoftibia.com/assets/25396329/9490f4e5-15d3-4054-8908-3438bddfa88c)


```html
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

    <!-- jquery -->
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <!-- Development -->
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>

    <title>PoC Discord Copy</title>

    <style>
        .tippy-content {
            padding: 0;
        }
    </style>
</head>

<body class="bg-dark text-white">

    <button id="myButton" class="d-none">tippy placeholder</button>

  
    <div class="container bg-dark">
        <div class="row pt-5 row-cols-2">
            <div class="col"></div>
            <div class="col">
                <div>
                    <a>Player: hi</a>
                    <p>Briasol: Ashari, Player and welcome to the Jewel Store of Ab'Dendriel.</p>
                    <a>Player: job</a>
                    <p>Briasol: I am a jeweller. I hope you are here for a trade.</p>

                </div>
            </div>
        </div>
    </div>


    <script>
        let cache_selection = null;
        let tooltipActive = false;
        let selection = null;
        const tippyTooltip = tippy(document.querySelector('#myButton'));

        $(document).on('mouseup', function (event) {
            selection = window.getSelection();
            // Check if the selection is different from the previous one or if the tooltip is not active
            // should also check if the selection is inside NPC/Books etc.
            if (selection.toString() !== cache_selection || !tooltipActive) {
                createTooltip(selection, event.clientX, event.clientY);
                cache_selection = selection.toString();
                tooltipActive = true;
            }
        });

        function createTooltip(selection, x, y) {
            // Check if there is any selected text
            if (selection.toString().length > 0) {
                // Position the tooltip at the mousedown location
                var top = y - 10; // Adjust as needed
                var left = x - 5; // Adjust as needed

                tippyTooltip.setProps({
                    arrow: false,
                    interactive: true,
                    allowHTML: true,
                    trigger: 'click',
                    content: '<button class="btn btn-primary btn-small rounded-0 bg-dark" onclick="copyForDiscord()">copy for discord</button> ',
                    getReferenceClientRect: () => ({
                        width: 100,
                        height: 100,
                        left: left,
                        right: left,
                        top: top,
                        bottom: top,
                    }),
                });

                tippyTooltip.show();
            }
        }

        function copyForDiscord() {
            const text = selection.toString();
            const discordText = text; // TODO: replace with discord formatting
            navigator.clipboard.writeText(discordText);
            tippyTooltip.setContent('<button class="btn btn-secondary rounded-0 btn-small bg-dark">copied!</button>');
            setTimeout(() => {
                tippyTooltip.setContent('<button class="btn btn-primary btn-small rounded-0 bg-dark" onclick="copyForDiscord()">copy for discord</button> ');
            }, 1000);

            
        }
    </script>
</body>

</html>

```
